[package]
name = "sidecar"
version = "0.1.1"
authors = ["Alex Kesling <alex@kesling.co>"]
edition = "2018"

[lib]
name = "sidecar"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.11.1"
features = ["extension-module"]
