[package]
name = "runtime"
version = "0.0.0"
edition = "2018"
authors = ["Alex Kesling <alex@kesling.co>"]

[[bin]]
name = "runtime"
path = "src/runtime.rs"

[dependencies]
draw = "0.3.0"
maplit = "1.0.2"
lazy_static = "1.4.0"
